I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 181, in script
    if b_guess == 1:
  File "game/script.rpy", line 181, in <module>
    if b_guess == 1:
NameError: name 'b_guess' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 181, in script
    if b_guess == 1:
  File "C:\Users\robin.peligry\Documents\renpy-8.3.2-sdk\renpy\ast.py", line 1843, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\robin.peligry\Documents\renpy-8.3.2-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\robin.peligry\Documents\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 181, in <module>
    if b_guess == 1:
NameError: name 'b_guess' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
Bluescreen 1.0
Wed Oct  9 14:52:23 2024
