I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 193, in script
    python:
  File "renpy/common/00start.rpy", line 194, in <module>
    renpy.execute_default_statement(True)
  File "game/script.rpy", line 12, in execute_default
    default b_pass = 0
Exception: store.b_pass is being given a default a second time.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 193, in script
    python:
  File "C:\Users\robin.peligry\Documents\renpy-8.3.2-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\robin.peligry\Documents\renpy-8.3.2-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 194, in <module>
    renpy.execute_default_statement(True)
  File "C:\Users\robin.peligry\Documents\renpy-8.3.2-sdk\renpy\exports\statementexports.py", line 372, in execute_default_statement
    i.execute_default(start)
  File "game/script.rpy", line 12, in execute_default
    default b_pass = 0
Exception: store.b_pass is being given a default a second time.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
Bluescreen 1.0
Mon Oct  7 17:16:04 2024
